# serverless.yaml 

service: moya-doc-assistant

provider:
  name: aws
  runtime: python3.11
  stage: dev
  region: us-east-1
  iam:
    role: arn:aws:iam::688736627613:role/MontyCloud-Common-Role

functions:
  app:
    handler: api/main.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: '/{proxy+}'
          method: ANY
          cors: true
    layers:
      - arn:aws:lambda:us-east-1:688736627613:layer:customeraccount-dev1-fastapi:382

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    layer: true
    slim: true