"""
Agent definitions for the Moya Trip Planner example.

Four specialist agents are created, all backed by a local Ollama model:

  destination_agent  — destination highlights, culture, weather
  itinerary_agent    — day-by-day travel plans
  budget_agent       — cost estimates and money-saving advice
  packing_agent      — personalised packing lists

Tool data is pre-fetched by the app layer (see app.py) and injected into
each agent's prompt as structured context, making the demo reliable with any
Ollama model regardless of its native tool-calling capability.

A fifth Ollama agent acts as the LLM-powered classifier that routes each
user query to the right specialist.
"""

import sys
from moya.agents.ollama_agent import OllamaAgent, OllamaAgentConfig
from moya.classifiers.llm_classifier import LLMClassifier
from moya.orchestrators.multi_agent_orchestrator import MultiAgentOrchestrator
from moya.registry.agent_registry import AgentRegistry

from .skills import local_tips_skill, travel_safety_skill

DEFAULT_MODEL = "gemma4:latest"
DEFAULT_BASE_URL = "http://localhost:11434"


def build_agents(model: str = DEFAULT_MODEL, base_url: str = DEFAULT_BASE_URL):
    """
    Construct and return the AgentRegistry and MultiAgentOrchestrator.

    Tool data is pre-fetched by the caller and injected into each message as
    structured context — see TripOrchestrator in app.py.

    :param model:    Ollama model tag (default: llama3.1:latest).
    :param base_url: Ollama server URL (default: http://localhost:11434).
    :returns:        (AgentRegistry, MultiAgentOrchestrator)
    """

    def _agent(name, description, system_prompt, skills=None):
        return OllamaAgent(OllamaAgentConfig(
            agent_name=name,
            agent_type="OllamaAgent",
            description=description,
            model_name=model,
            base_url=base_url,
            system_prompt=system_prompt,
            skills=skills or [],
        ))

    # -----------------------------------------------------------------------
    # 1. Destination Research Agent
    #    Skills: travel_safety_skill (prompt-only)
    # -----------------------------------------------------------------------
    destination_agent = _agent(
        name="destination_agent",
        description=(
            "Destination research specialist — provides highlights, culture, "
            "cuisine, transport, and weather for any city or country"
        ),
        system_prompt=(
            "You are an enthusiastic travel destination expert. "
            "The user's message includes a [TRAVEL DATA] section with factual information "
            "about the destination retrieved from our travel database. "
            "Use this data as the foundation of your response. "
            "Expand on it with engaging commentary, insider knowledge, and practical tips. "
            "Be warm, inspiring, and genuinely helpful."
        ),
        skills=[travel_safety_skill],
    )

    # -----------------------------------------------------------------------
    # 2. Itinerary Planning Agent
    #    Skills: local_tips_skill (prompt-only in this architecture)
    # -----------------------------------------------------------------------
    itinerary_agent = _agent(
        name="itinerary_agent",
        description=(
            "Itinerary planning specialist — creates structured day-by-day "
            "travel schedules tailored to interests and trip length"
        ),
        system_prompt=(
            "You are an expert travel itinerary planner. "
            "The user's message includes a [TRAVEL DATA] section with a day-by-day framework "
            "and insider tips generated by our planning tools. "
            "Expand this framework into a rich, detailed itinerary. "
            "Add timing suggestions, nearby dining options, and practical advice for each day. "
            "Make it feel like advice from a friend who knows the destination intimately."
        ),
        skills=[local_tips_skill],
    )

    # -----------------------------------------------------------------------
    # 3. Budget Planning Agent
    # -----------------------------------------------------------------------
    budget_agent = _agent(
        name="budget_agent",
        description=(
            "Travel budget specialist — estimates accommodation, food, transport, "
            "and activity costs; provides money-saving strategies"
        ),
        system_prompt=(
            "You are a savvy travel budget expert. "
            "The user's message includes a [TRAVEL DATA] section with a cost breakdown "
            "from our budget estimation tool. "
            "Present this data clearly, then add 4-5 specific, actionable money-saving tips "
            "for the destination. Explain where it's worth splurging and where to economise."
        ),
    )

    # -----------------------------------------------------------------------
    # 4. Packing Agent
    # -----------------------------------------------------------------------
    packing_agent = _agent(
        name="packing_agent",
        description=(
            "Packing specialist — recommends what to pack based on destination, "
            "weather, and trip length; emphasises packing light and smart"
        ),
        system_prompt=(
            "You are a professional travel packing expert. "
            "The user's message includes a [TRAVEL DATA] section with weather conditions "
            "and a packing list generated by our tools. "
            "Present the packing list clearly, then add tips on what NOT to pack, "
            "how to save luggage space, and any destination-specific items often overlooked."
        ),
    )

    # -----------------------------------------------------------------------
    # Register specialist agents
    # -----------------------------------------------------------------------
    registry = AgentRegistry()
    registry.register_agent(destination_agent)
    registry.register_agent(itinerary_agent)
    registry.register_agent(budget_agent)
    registry.register_agent(packing_agent)

    # -----------------------------------------------------------------------
    # Classifier Agent — routes queries to the correct specialist
    # -----------------------------------------------------------------------
    classifier_agent = OllamaAgent(OllamaAgentConfig(
        agent_name="trip_classifier",
        agent_type="OllamaAgent",
        description="Internal classifier — routes trip planning queries to specialist agents",
        model_name=model,
        base_url=base_url,
        system_prompt=(
            "You are a query router for a trip planning system. "
            "Your ONLY task is to output the name of the most appropriate specialist agent. "
            "Return ONLY the agent name — no explanation, no punctuation, no extra text.\n\n"
            "Routing rules:\n"
            "  destination_agent : destination facts, highlights, culture, cuisine, weather, "
            "'what to know', 'tell me about', 'what is it like'\n"
            "  itinerary_agent   : day plans, schedules, 'what to do', 'how to spend', "
            "'day by day', 'itinerary', 'plan my trip', 'create a plan'\n"
            "  budget_agent      : costs, money, prices, 'how much', expenses, "
            "'can I afford', 'budget', 'cheap', 'expensive'\n"
            "  packing_agent     : packing, luggage, 'what to bring', clothes, gear, "
            "suitcase, 'what to wear', 'what to pack'\n\n"
            "Output ONLY one of: destination_agent, itinerary_agent, budget_agent, packing_agent"
        ),
    ))

    # Verify Ollama is reachable
    try:
        classifier_agent.setup()
    except ConnectionError as exc:
        print(f"\nCannot connect to Ollama at {base_url}: {exc}")
        print("\nTo fix this:")
        print("  1. Start Ollama:   ollama serve")
        print(f"  2. Pull the model: ollama pull {model}")
        sys.exit(1)

    classifier = LLMClassifier(classifier_agent, default_agent="destination_agent")

    orchestrator = MultiAgentOrchestrator(
        agent_registry=registry,
        classifier=classifier,
        default_agent_name="destination_agent",
    )

    return registry, orchestrator
